services:
  receiptman:
    build:
      context: .
    container_name: receiptman
    volumes:
      - ./www:/var/www
      - ./output:/var/www/output
      - ./.ssh:/root/.ssh
    ports:
      - 2002:80
    working_dir: /var/www
