services:
  receiptman:
    build:
      context: .
    container_name: receiptman
    volumes:
      - ./www:/var/www
      - ./output:/var/www/output
    ports:
      - 2002:80
  receiptman_db:
    image: mysql:latest
    container_name: receiptman_db
    environment:
      - MYSQL_ROOT_PASSWORD=receiptmanpassword
    ports:
      - 974:3306
