#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\Command\{
    ReceiptDebianCommand,
    PhpFullDev,
    Python,
    Node,
    Nginx,
    Apache,
    DotNet,
    PhpCommand
};
use App\Command\Dev\AddNew;
use Symfony\Component\Filesystem\Filesystem;

require_once './vendor/autoload.php';

$fileSystem = new Filesystem();

$application = new Application();
$application->add(new PhpFullDev($fileSystem));
$application->add(new ReceiptDebianCommand($fileSystem));
$application->add(new Python($fileSystem));
$application->add(new Node($fileSystem));
$application->add(new Nginx($fileSystem));
$application->add(new Apache($fileSystem));
$application->add(new DotNet($fileSystem));
$application->add(new PhpCommand($fileSystem));
$application->add(new AddNew());

$application->run();
