#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\Command\{
    ReceiptDebianCommand,
    PhpFullDevCommand,
    PythonCommand,
    NodeCommand,
    NginxCommand,
    ApacheCommand,
    DotNetCommand,
    PhpCommand,
    PostgreCommand
};
use App\Command\Dev\AddNew;
use Symfony\Component\Filesystem\Filesystem;

require_once './vendor/autoload.php';

$fileSystem = new Filesystem();

$application = new Application();
$application->add(new PhpFullDevCommand($fileSystem));
$application->add(new ReceiptDebianCommand($fileSystem));
$application->add(new PythonCommand($fileSystem));
$application->add(new NodeCommand($fileSystem));
$application->add(new NginxCommand($fileSystem));
$application->add(new ApacheCommand($fileSystem));
$application->add(new DotNetCommand($fileSystem));
$application->add(new PhpCommand($fileSystem));
$application->add(new PostgreCommand($fileSystem));
$application->add(new AddNew());

$application->run();
