services:
  endpoints_recaller:
    build:
      context: .
    container_name: endpoints_recaller
    volumes:
      - ./www:/var/www
    ports:
      - 2000:80
  endpoints_recaller_db:
    image: mysql:latest
    container_name: endpoints_recaller_db
    environment:
      - MYSQL_ROOT_PASSWORD=erpassword
    ports:
      - 972:3306
